### ISSUE TITLE
2.1.E: лишнее приведение типов

### ISSUE THREAD

**Issue by oogl** [Nhsdkk/Yandex_Python#11]
Уже обсуждали в лс излишнее приведение к `int` итогового результата в строке 3:

https://github.com/Nhsdkk/Yandex_Python/blob/c1cbf92e98cad278111d03e539692ee952fb0976/2_1_section/E_store.py#L1-L3

Причина: сумма и произведение двух целых чисел всегда будет целым числом. Это, вроде, называется свойством [замыкания](https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%BC%D1%8B%D0%BA%D0%B0%D0%BD%D0%B8%D0%B5_(%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B0)) целых чисел

**Comment by Nhsdkk** [comment]
Уже пофиксил в ветке 3_3_section в коммите fix:unnecessary complexity fix
