### ISSUE TITLE
3.4.А: использование `enumerate()` вместо `for i in range(len(...))`

### ISSUE THREAD

**Issue by oogl** [Nhsdkk/Yandex_Python#14]
В питоне есть встроенная функция [enumerate()](https://docs.python.org/3/library/functions.html#enumerate), которая возращает сразу и номер итерации, и объект. Таким образом, можно заменить строку 3:

https://github.com/Nhsdkk/Yandex_Python/blob/1fb710d2fcf864d567501a07c18ff8be9ff7385d/3_4_section/A_list_automation.py#L1-L3

вот так:

```python
print("\n".join([f"{i}. {word}" for i, word in enumerate(splitted_string, start=1)]))
```

**Comment by Nhsdkk** [comment]
Пофиксил в последнем коммите

**Comment by oogl** [comment]
b11bf47a8eb4d65b887fba4883394d5008af65a7
